version: "3.7"

services: 
  ics:
    container_name: ics
    build: 
      context: .
      dockerfile: docker/prod.dockerfile
    env_file: 
      - .env
    ports:
      - "8080:8080"
      
  mongo:
    container_name: mongodb
    image: mongo:4.4
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data/db/mongo:/data/mongo
    env_file:
      - .env

  redis:
    container_name: redisdb
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes: 
      - ./data/db/redis:/data/redis
    env_file:
      - .env
    command: redis-server --appendonly yes --requirepass $REDIS_PWD

  
