apiVersion: v1
kind: Service
metadata:
  name: icsharing-server
  labels:
    app: icsharing
spec:
  type: LoadBalancer
  ports:
  - port: 443
  selector:
    app: icsharing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icsharing-server
spec:
  selector:
    matchLabels:
      app: icsharing
  replicas: 3
  template:
    metadata:
      labels:
        app: icsharing
      spec:
        containers:
        - name: icsharing
          image: linkc0829/go-icsharing:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 443
          envFrom:
          - configMapRef:
            name: env-configmap
          - secretRef:
            name: env-secrets

