apiVersion: v1
kind: Service
metadata:
  name: redisdb
  labels: 
    app: redis
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: redis
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisdb
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    labels:
      app: redis
    spec:
      containers:
      - name: redisdb
        image: redis:alpine
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
        envFrom:
          - configMapRef:
            name: env-configmap
          - secretRef:
            name: env-secrets