// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type User struct {
	ID      *string `json:"id" bson:"_id"`
	Email   *string `json:"email"`
	UserID  *string `json:"userId"`
	Friends []*User `json:"friends"`
}

type UserInput struct {
	Email  *string `json:"email"`
	UserID *string `json:"userId"`
}
